name: Android CI

on:
  push:

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Read secrets
      env:
        GITHUB_ACTOR_TEST: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN_TEST: ${{ secrets.GITHUB_TOKEN }}
      run: echo GITHUB_ACTOR_TEST=\"$GITHUB_ACTOR_TEST\" GITHUB_TOKEN_TEST=\"$GITHUB_TOKEN_TEST\"
